---
project_name: pennywise

release:
  github:
    owner: kaytu-io
    name: pennywise

checksum: {}

builds:
  - binary: pennywise
    ldflags:
      - -s -w -X github.com/kaytu-io/pennywise/cmd/predef.VERSION={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./main.go

archives:
  - id: binary
    format: binary
  - id: default
    format: tar.gz

signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    args:
      - "sign-blob"
      - "--key=env://COSIGN_SECRET"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: all
