---
project_name: pennywise

release:
  github:
    owner: kaytu-io
    name: pennywise

checksum: {}

builds:
  - binary: pennywise
    ldflags:
      - -s -w -X cmd/predef/version.VERSION={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./main.go

archives:
  - id: binary
    format: binary
  - id: default
    builds: [linux, darwin]
    format: tar.gz
  - id: windows
    builds: [windows]
    format: zip